version: "3.9"

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - "${APP_PORT}:8080"
        volumes:
            - .:/var/www/html

networks:
    default:
        name: test-network
        driver: bridge
        driver_opts:
            com.docker.network.driver.mtu: ${MTU}
